
--creating table RAW_PHARMA for CSV --

CREATE OR REPLACE TABLE RAW_PHARMA (
   DRUG_ID STRING PRIMARY KEY,
   DRUG_NAME STRING NOT NULL,
   GENERIC_NAME STRING,
   MANUFACTURER STRING,
   DOSAGE_FORM STRING,
   STRENGTH_MG NUMBER(10,2),
   PRICE_INR NUMBER(10,2),
   APPROVAL_DATE DATE,
   EXPIRY_DATE DATE,
   BATCH_NUMBER STRING,
   QUANTITY_IN_STOCK NUMBER,
   THERAPEUTIC_AREA STRING,
   PRESCRIPTION_REQUIRED STRING,
   ATC_CODE STRING,
   STORAGE_TEMP_C STRING
);


--created STG TABLE


CREATE OR REPLACE TABLE STG_PHARMA (
   DRUG_ID STRING PRIMARY KEY,
   DRUG_NAME STRING NOT NULL,
   GENERIC_NAME STRING,
   MANUFACTURER STRING,
   DOSAGE_FORM STRING,
   STRENGTH_MG NUMBER(10,2),
   PRICE_INR NUMBER(10,2),
   APPROVAL_DATE DATE,
   EXPIRY_DATE DATE,
   BATCH_NUMBER STRING,
   QUANTITY_IN_STOCK NUMBER,
   THERAPEUTIC_AREA STRING,
   PRESCRIPTION_REQUIRED STRING,
   ATC_CODE STRING,
   STORAGE_TEMP_C STRING
);

--creating GOLD_PHARMA SCHEMA 

CREATE OR REPLACE TABLE GOLD_PHARMA (
   DRUG_ID STRING PRIMARY KEY,
   DRUG_NAME STRING NOT NULL,
   GENERIC_NAME STRING,
   MANUFACTURER STRING,
   DOSAGE_FORM STRING,
   STRENGTH_MG NUMBER(10,2),
   PRICE_INR NUMBER(10,2),
   APPROVAL_DATE DATE,
   EXPIRY_DATE DATE,
   BATCH_NUMBER STRING,
   QUANTITY_IN_STOCK NUMBER,
   THERAPEUTIC_AREA STRING,
   PRESCRIPTION_REQUIRED STRING,
   ATC_CODE STRING,
   STORAGE_TEMP_C STRING
);

-- creating unioned table --

CREATE
OR REPLACE TABLE RAW_PHARMA_UNIONED AS
SELECT
  DRUG_ID,
  DRUG_NAME,
  GENERIC_NAME,
  MANUFACTURER,
  DOSAGE_FORM,
  STRENGTH_MG,
  PRICE_INR,
  APPROVAL_DATE,
  EXPIRY_DATE,
  BATCH_NUMBER,
  QUANTITY_IN_STOCK,
  THERAPEUTIC_AREA,
  PRESCRIPTION_REQUIRED,
  ATC_CODE,
  STORAGE_TEMP_C
FROM
  RAW_PHARMA_JSON_TABULAR
UNION ALL
SELECT
  DRUG_ID,
  DRUG_NAME,
  GENERIC_NAME,
  MANUFACTURER,
  DOSAGE_FORM,
  STRENGTH_MG,
  PRICE_INR,
  APPROVAL_DATE,
  EXPIRY_DATE,
  BATCH_NUMBER,
  QUANTITY_IN_STOCK,
  THERAPEUTIC_AREA,
  PRESCRIPTION_REQUIRED,
  ATC_CODE,
  STORAGE_TEMP_C
FROM
  RAW_PHARMA;


-- created store procdure for parameterized copy activity

CREATE OR REPLACE PROCEDURE copy_data(table_name STRING, stage_name STRING, file_type STRING, file_name STRING)
RETURNS STRING
LANGUAGE SQL
AS
BEGIN
    EXECUTE IMMEDIATE
    'COPY INTO ' || table_name ||
    ' FROM @' || stage_name || '/' || file_name ||' 
    FILE_FORMAT = (TYPE = '''|| file_type ||''')'||'ON_ERROR =''CONTINUE''';
    RETURN 'Copy completed successfully!';
    END;


